logging:
  level:
    liquibase: DEBUG
    org.springframework.boot.autoconfigure.liquibase: DEBUG

spring:
  application:
    name: offers

  datasource:
    url: jdbc:postgresql://localhost:5432/offers
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: offres

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
    default-schema: offres
